
23.0 - Manejo de exceções

O manejo de exceções nos permite capturar e lidar com erros de maneira controlada utilizando 
as declarações try, except e opcionalmente finally.

 
- Try:
O bloco try contém o código que pode gerar uma exceção. Se ocorrer uma exceção dentro do bloco try, o fluxo de execução é transferido para o bloco except correspondente.


- Except:
O bloco except especifica o tipo de exceção que se deseja capturar e lidar. Você pode ter múltiplos blocos except para lidar com diferentes tipos de exceções.


- Finally:
O bloco finally é opcional e é executado sempre, independentemente de ter ocorrido uma exceção ou não. É comumente utilizado para realizar tarefas de limpeza ou liberação de recursos.


Exceções Integradas em Python

Python possui várias exceções integradas que cobrem uma ampla gama de erros comuns. Alguns exemplos incluem:

- ValueError: Ocorre quando uma função recebe um argumento do tipo correto, mas com valor inadequado.
- TypeError: Ocorre quando uma operação ou função é aplicada a um objeto de tipo inadequado.
- IndexError: Ocorre ao tentar acessar um índice fora dos limites de uma lista ou tupla.
- KeyError: Ocorre quando uma chave não é encontrada em um dicionário.
- FileNotFoundError: Ocorre quando o código tenta acessar um arquivo que não existe.